Untabification

diff --git a/backlight-adaptive b/backlight-adaptive
--- a/backlight-adaptive
+++ b/backlight-adaptive
@@ -56,84 +56,84 @@ done
 # Either read existing or create new config
 if [ -n "${config_dir}" ]
 then
-	config_file="${config_dir}/${progname}"
-	if [ -f "${config_file}" ]
-	then
-	        { while IFS='=' read name v; do
-        	        case $name in
-	                acpi_dev    ) acpi_dev="$v";     continue;;
-                	backend_args) backend_args="$v"; continue;;
-        	        backends    ) backends="$v";     continue;;
-	                delay       ) delay="$v";        continue;;
-                	grab        ) grab="$v";         continue;;
-        	        log_level   ) log_level="$v";    continue;;
-			log_color   ) log_color="$v";    continue;;
-	                maxbright   ) maxbright="$v";    continue;;
-        	        max_color   ) max_color="$v";    continue;;
-	                minbright   ) minbright="$v";    continue;;
-                	esac
-        	done; } < ~/.config/${progname}
-	elif touch "${config_file}"; then
-        	print_options delay grab log_level log_color max_color maxbright minbright acpi_dev backends backend_args | sort > "${config_file}"
-	else
-		unset config_file
-	fi
+        config_file="${config_dir}/${progname}"
+        if [ -f "${config_file}" ]
+        then
+                { while IFS='=' read name v; do
+                        case $name in
+                        acpi_dev    ) acpi_dev="$v";     continue;;
+                        backend_args) backend_args="$v"; continue;;
+                        backends    ) backends="$v";     continue;;
+                        delay       ) delay="$v";        continue;;
+                        grab        ) grab="$v";         continue;;
+                        log_level   ) log_level="$v";    continue;;
+        		log_color   ) log_color="$v";    continue;;
+                        maxbright   ) maxbright="$v";    continue;;
+                        max_color   ) max_color="$v";    continue;;
+                        minbright   ) minbright="$v";    continue;;
+                        esac
+                done; } < ~/.config/${progname}
+        elif touch "${config_file}"; then
+                print_options delay grab log_level log_color max_color maxbright minbright acpi_dev backends backend_args | sort > "${config_file}"
+        else
+        	unset config_file
+        fi
 fi
 
 show_help() {
-	echo "Usage: $(basename $0) [options] -- [backend options]"
-	echo "Options:"
-	echo "-d, --delay     FLOAT       Snapshots delay (seconds)"
-	echo "-g, --no-grab               Don't keep camera busy all time"
-	echo "-A, --no-acpi               Don't use ACPI directly"
-	echo "-a, --acpi-dev  NAME        ACPI device to be controlled"
-	echo "-v, --video-dev DEVICE      Video device used as sensor (e.g. /dev/video0)"
-	echo "-b, --backends  STR,STR...  Comma-separated list of backlight control backends"
-	echo "-B, --list-backends         List available backends"
-	echo "-l, --log       STRING      Log verbosity. One of: error, warning, info, debug"
-	echo "-c, --color     BOOLEAN     Colorize output"
-	echo "    --bl-max    FLOAT       Maximum backlight level (%)"
-	echo "    --bl-min    FLOAT       Minimum backlight level (%)"
-	echo "    --max-color INTEGER     Color value for full backlight level"
-	echo "-h, --help                  Show this help"
+        echo "Usage: $(basename $0) [options] -- [backend options]"
+        echo "Options:"
+        echo "-d, --delay     FLOAT       Snapshots delay (seconds)"
+        echo "-g, --no-grab               Don't keep camera busy all time"
+        echo "-A, --no-acpi               Don't use ACPI directly"
+        echo "-a, --acpi-dev  NAME        ACPI device to be controlled"
+        echo "-v, --video-dev DEVICE      Video device used as sensor (e.g. /dev/video0)"
+        echo "-b, --backends  STR,STR...  Comma-separated list of backlight control backends"
+        echo "-B, --list-backends         List available backends"
+        echo "-l, --log       STRING      Log verbosity. One of: error, warning, info, debug"
+        echo "-c, --color     BOOLEAN     Colorize output"
+        echo "    --bl-max    FLOAT       Maximum backlight level (%)"
+        echo "    --bl-min    FLOAT       Minimum backlight level (%)"
+        echo "    --max-color INTEGER     Color value for full backlight level"
+        echo "-h, --help                  Show this help"
 }
 
 # Arguments loading
 
 while [ $# -gt 0 ]; do
-	case $1 in
-	'-d' | '--delay' ) delay="$2"
-		shift ;;
-	'-g' | '--no-grab' ) grab=false ;;
-	'-A' | '--no-acpi' ) acpi=false ;;
-	'-l' | '--log' )   log_level=$2
-		shift ;;
-	'-c' | '--color'   )
-		case "$2" in
-		true ) log_color=true;;
-		false) log_color=false;;
-		esac
-		shift ;;
-	'--bl-max' )  maxbright="$2"
-		shift ;;
-	'--bl-min' ) minbright="$2"
-		shift ;;
-	'--max-color' )	max_color="$2"
-		shift ;;
-	'-a' | '--acpi-dev' ) acpi_dev="$2"
-		shift ;;
-	'-v' | '--video-dev' ) vdev="$2"
-		shift ;;
-	'-b' | '--backends' ) backends="$2"
-		shift ;;
-	'-B' | '--list-backends' ) echo "${backends_all}"
-		exit ;;
-	'-h' | '--help' ) show_help
-		exit ;;
-	'--' ) backend_args="$*"
-		break ;;
-	esac
-	shift
+        case $1 in
+        '-d' | '--delay' ) delay="$2"
+        	shift ;;
+        '-g' | '--no-grab' ) grab=false ;;
+        '-A' | '--no-acpi' ) acpi=false ;;
+        '-l' | '--log' )   log_level=$2
+        	shift ;;
+        '-c' | '--color'   )
+        	case "$2" in
+        	true ) log_color=true;;
+        	false) log_color=false;;
+        	esac
+        	shift ;;
+        '--bl-max' )  maxbright="$2"
+        	shift ;;
+        '--bl-min' ) minbright="$2"
+        	shift ;;
+        '--max-color' )	max_color="$2"
+        	shift ;;
+        '-a' | '--acpi-dev' ) acpi_dev="$2"
+        	shift ;;
+        '-v' | '--video-dev' ) vdev="$2"
+        	shift ;;
+        '-b' | '--backends' ) backends="$2"
+        	shift ;;
+        '-B' | '--list-backends' ) echo "${backends_all}"
+        	exit ;;
+        '-h' | '--help' ) show_help
+        	exit ;;
+        '--' ) backend_args="$*"
+        	break ;;
+        esac
+        shift
 done
 
 # Configure terminal font controls
@@ -200,97 +200,97 @@ msg_info "Config file: ${bold}$(col green)${config_file}"
 
 msg_info "Checking dependencies"
 for dep in ffmpeg tr hexdump awk; do
-	if ! [ "$(which $dep 2>/dev/null)" ]; then
-		msg_error "${dep} executable required but not found"
-		abort=1
-	fi
+        if ! [ "$(which $dep 2>/dev/null)" ]; then
+        	msg_error "${dep} executable required but not found"
+        	abort=1
+        fi
 done
 if [ "$abort" ]; then
-	exit 1
+        exit 1
 fi
 
 # Choose backlight control tool
 
 msg_info "Searching usable backend"
 if [ ! "${backends}" ]; then
-	fatal "Backends are not set"
+        fatal "Backends are not set"
 fi
 backends="$( echo "$backends" | tr ',' ' ' )"
 for backend in $backends; do
-	msg_info "Checking backend ${bold}$(col green)$backend"
-	case "$backend" in
-	light )
-		which ${backend} >/dev/null 2>&1 || continue
-		bl_cmd='light -S '
-		break
-	;;
-	xbacklight )
-		which ${backend} >/dev/null 2>&1 || continue
-		bl_cmd='xbacklight -set '
-		break
-	;;
-	internal )
-		acpi_dir="/sys/class/backlight"
+        msg_info "Checking backend ${bold}$(col green)$backend"
+        case "$backend" in
+        light )
+        	which ${backend} >/dev/null 2>&1 || continue
+        	bl_cmd='light -S '
+        	break
+        ;;
+        xbacklight )
+        	which ${backend} >/dev/null 2>&1 || continue
+        	bl_cmd='xbacklight -set '
+        	break
+        ;;
+        internal )
+        	acpi_dir="/sys/class/backlight"
 
-		# ACPI dir exists and is not empty
-		if ! [ -d "${acpi_dir}" ] ; then
-			msg_error "No ACPI support found"
-			break
-		fi
+        	# ACPI dir exists and is not empty
+        	if ! [ -d "${acpi_dir}" ] ; then
+        		msg_error "No ACPI support found"
+        		break
+        	fi
 
 
-		# Use first entry if acpi_dev not set
-		if [ "${acpi_dev}" ] && { [ -d "${acpi_dir}/${acpi_dev}" ] || ! msg_warning "ACPI device ${acpi_dev} not found"; }; then
-			acpi_dir="${acpi_dir}/${acpi_dev}"
-		else
-			for acpi_dir in "${acpi_dir}"/* ; do break; done
-			if ! [ -d "${acpi_dir}" -a -f "${acpi_dir}/brightness" ]; then
-				msg_error "No ACPI backlight devices found"
-				break
-			fi
-		fi
-		
-		# Translate brightness limits to raw backlight range
-		maxbright=$(( maxbright * $(cat ${acpi_dir}/max_brightness) / 100 ))
-        	minbright=$(( minbright * $(cat ${acpi_dir}/max_brightness) / 100 ))
+        	# Use first entry if acpi_dev not set
+        	if [ "${acpi_dev}" ] && { [ -d "${acpi_dir}/${acpi_dev}" ] || ! msg_warning "ACPI device ${acpi_dev} not found"; }; then
+        		acpi_dir="${acpi_dir}/${acpi_dev}"
+        	else
+        		for acpi_dir in "${acpi_dir}"/* ; do break; done
+        		if ! [ -d "${acpi_dir}" -a -f "${acpi_dir}/brightness" ]; then
+        			msg_error "No ACPI backlight devices found"
+        			break
+        		fi
+        	fi
+        	
+        	# Translate brightness limits to raw backlight range
+        	maxbright=$(( maxbright * $(cat ${acpi_dir}/max_brightness) / 100 ))
+                minbright=$(( minbright * $(cat ${acpi_dir}/max_brightness) / 100 ))
 
-		break
-	;;
-	esac
-	backend=
+        	break
+        ;;
+        esac
+        backend=
 done
 if [ ! "${backend}" ]; then
-	fatal "No working backends found"
+        fatal "No working backends found"
 fi
 msg_info "Using backend ${bold}$(col green)${backend}"
 
 # Setup temporary dir
 
 for path in "/var/run" "${XDG_RUNTIME_DIR}" "/tmp" "~/.cache"; do
-	# Check base path
-	[ "${path}" -a -d "${path}" -a -w "${path}" ] || continue
-	tmpdir="${path}/${progname}"
-	pidfile="$tmpdir/pid"
-	break
+        # Check base path
+        [ "${path}" -a -d "${path}" -a -w "${path}" ] || continue
+        tmpdir="${path}/${progname}"
+        pidfile="$tmpdir/pid"
+        break
 done
 # No place for tmpdir
 if [ ! "${tmpdir}" ]; then
-	fatal "Can't find place for temporary directory"
+        fatal "Can't find place for temporary directory"
 fi
 msg_info "Temporary directory: ${bold}$(col green)${tmpdir}"
 
 if [ ! -e "${tmpdir}" ]; then
-	mkdir -p "${tmpdir}"
+        mkdir -p "${tmpdir}"
 elif ! [ -d "${path}" -a -w "${path}" ]; then
-	fatal "$tmpdir: Not a directory"
+        fatal "$tmpdir: Not a directory"
 elif [ -f "$pidfile" ]; then
-	# We are singleton
+        # We are singleton
 
-	read pid < $pidfile
-	if [ "$pid" -a "$(ps $pid | grep $pid)" ] ; then
-		msg_warning "Found runing instance, exiting."
-		exit
-	fi
+        read pid < $pidfile
+        if [ "$pid" -a "$(ps $pid | grep $pid)" ] ; then
+        	msg_warning "Found runing instance, exiting."
+        	exit
+        fi
 fi
 
 echo "$$" > "$pidfile"
@@ -303,33 +303,33 @@ frames=$($grab || echo -frames 1)
 bl_mul=$( echo | awk "{print $max_color / 255}" )
 ffmpeg_cmd='stdbuf -o0 ffmpeg -v debug -f v4l2 -s 1x1 -i "${vdev}" ${frames} -vcodec rawvideo -vf scale="1:1",curves=all="0/0 ${bl_mul}/1",lutyuv="u=128:v=128" -f rawvideo -pix_fmt gray -r 1/${delay} -'
 ( { 
-	if $grab; then
-		eval exec "${ffmpeg_cmd}"
-	else while sleep $delay & tpid=$!; do
-		eval "${ffmpeg_cmd}"
-		wait $tpid;
-	done; fi
+        if $grab; then
+        	eval exec "${ffmpeg_cmd}"
+        else while sleep $delay & tpid=$!; do
+        	eval "${ffmpeg_cmd}"
+        	wait $tpid;
+        done; fi
   } </dev/null 2>/dev/null |\
-	stdbuf -o0 tr -s "$(printf "[\%03o-\%03o]" 0 255 )"  |\
-	$b hexdump -e '1/1 "%u\n"'                           |\
-	$b awk \
-	-v "quiet=$([ $log_level -ge $debug ] && echo 0 || echo 1)" \
-	-v "ctl_file=${acpi_dir}/brightness"                        \
-	-v "bl_cmd=${bl_cmd}"                                       \
-	-v "bl_args=${backend_args}"                                \
-	'{
-		bl = $1 * '${maxbright}' / 255
-		bl = bl > '${maxbright}' ? '${maxbright}' : bl < '${minbright}' ? '${minbright}' : bl
-		if (! quiet) {
+        stdbuf -o0 tr -s "$(printf "[\%03o-\%03o]" 0 255 )"  |\
+        $b hexdump -e '1/1 "%u\n"'                           |\
+        $b awk \
+        -v "quiet=$([ $log_level -ge $debug ] && echo 0 || echo 1)" \
+        -v "ctl_file=${acpi_dir}/brightness"                        \
+        -v "bl_cmd=${bl_cmd}"                                       \
+        -v "bl_args=${backend_args}"                                \
+        '{
+        	bl = $1 * '${maxbright}' / 255
+        	bl = bl > '${maxbright}' ? '${maxbright}' : bl < '${minbright}' ? '${minbright}' : bl
+        	if (! quiet) {
                         printf ("brightness: %.02f%% value: %u\n", 100 * bl / '${maxbright}', $1)
                 }
-		if (bl_cmd) {
-			system (bl_cmd bl bl_args)
-			next
-		}
-		printf ("%u\n",bl) > ctl_file
-		fflush (ctl_file)
-	}'
+        	if (bl_cmd) {
+        		system (bl_cmd bl bl_args)
+        		next
+        	}
+        	printf ("%u\n",bl) > ctl_file
+        	fflush (ctl_file)
+        }'
 ) & procpid=$!
 
 # Event handlers
@@ -340,12 +340,12 @@ kill_quiet() { {
 } 2>/dev/null; }
 
 quit() {
-	state=int
+        state=int
         kill_quiet $procpid
 }
 
 restart() {
-	state=restart
+        state=restart
         kill_quiet $procpid
 }
 
@@ -355,9 +355,9 @@ trap "restart" USR1
 
 # Monitor config changes
 if [ -n "$config_file" ]; then {
-	inotifywait -q -e modify "$config_file"
-	msg_info "Configuration changed"
-	kill -s USR1 $$
+        inotifywait -q -e modify "$config_file"
+        msg_info "Configuration changed"
+        kill -s USR1 $$
 } & monpid=$!; fi
 
 # Waiting
@@ -368,13 +368,13 @@ kill_quiet $monpid
 
 case $state in
 'int'    )
-	msg_info Interrupted; 
-	exit ;;
+        msg_info Interrupted; 
+        exit ;;
 'restart')
-	msg_info 'Restart...'; rm $pidfile; 
-	eval exec "$0 $startup_args" ;;
+        msg_info 'Restart...'; rm $pidfile; 
+        eval exec "$0 $startup_args" ;;
 'run'    )
-	msg_warning 'Pipeline terminated on its own'; 
-	exit ;;
+        msg_warning 'Pipeline terminated on its own'; 
+        exit ;;
 esac
 
