Style and quoting

diff --git a/backlight-adaptive b/backlight-adaptive
--- a/backlight-adaptive
+++ b/backlight-adaptive
@@ -65,22 +65,22 @@ h_grp() {
 
 set_num() {
         if isnum "$2"; then
-                eval $1="'$2'"
+                eval "$1='$2'"
         fi
 }
 set_bool() {
         case "$2" in true | false )
-                eval $1="'$2'"
+                eval "$1='$2'"
         esac
 }
 set_int_list() {
         case "$2" in [0-9,]* )
-                eval $1="'$2'"
+                eval "$1='$2'"
         esac
 }
 
 cmd_avail() {
-        type $1 > /dev/null 2>&1
+        type "$1" >/dev/null 2>&1
         return $?
 }
 
@@ -88,7 +88,7 @@ cmd_avail() {
 
 print_options() {
         while [ $# -gt 0 ]; do
-                eval print "$1=\$$1"
+                eval "print $1=\${$1}"
                 shift
         done
 }
@@ -97,7 +97,7 @@ save_config() {
 }
 
 # Search for either config file or writable config dir
-for config_dir in "${XDG_CONFIG_PATH}" ~/.config /etc ; do
+for config_dir in "${XDG_CONFIG_PATH}" "$HOME/.config" '/etc' ; do
         [ -f "${config_dir}/${progname}" -o \( -d "${config_dir}" -a -w "${config_dir}" \) ] && break ||:
         config_dir=
 done
@@ -127,7 +127,7 @@ then
                                 print "Unknown config option '${name}'"
                                 continue;;
                         esac
-                done; } < ~/.config/${progname}
+                done; } < "$HOME/.config/${progname}"
         elif touch "${config_file}"; then
                 save_config
         else
@@ -180,42 +180,39 @@ show_help() {
 }
 
 while [ $# -gt 0 ]; do
-        case $1 in
-        '-d' | '--delay' ) set_num delay "$2";             shift ;;
-        '-S' | '--skip'  ) set_num skip "$2";              shift ;;
-        '-1' | '--onetime' ) onetime=true ;;
-        '-l' | '--log' ) log_level="$2";                   shift ;;
-        '-c' | '--color'   ) set_bool log_color "$2";      shift ;;
-        '-M' | '--bl-max' ) set_num maxbright "$2";        shift ;;
-        '-m' | '--bl-min' ) set_num minbright "$2";        shift ;;
-        '-C' | '--max-color' ) set_num max_color "$2";     shift ;;
-        '--calibrate' ) ctl_action=cal ;;
-        '-s' | '--smooth' ) set_int_list fade_frames "$2"; shift ;;
-        '-T' | '--threshold') set_int threshold "$2";      shift ;;
-        '-a' | '--acpi-dev' ) acpi_dev="$2";               shift ;;
-        '-v' | '--video-dev' ) vdev="$2";                  shift ;;
-        '-b' | '--backends' ) backends="$2";               shift ;;
-        '-B' | '--list-backends' ) print "${backends_all}"
-                exit ;;
-        '-t' | '--toggle' ) ctl_action=toggle;;
-        '-w' | '--watchconf' ) set_bool watch_conf "$2";   shift ;;
-        '-u' | '--update-conf' ) save_config ;;
-        '-p' | '--pretend' ) ctl_action=pretend ;;
-        '-h' | '--help' ) show_help
-                exit ;;
-        '--' ) backend_args="$*"
-                break ;;
-        *    ) echo "Invalid option '$1'" ;;
+        case "$1" in
+        '-d' | '--delay'         ) set_num delay "$2";            shift ;;
+        '-S' | '--skip'          ) set_num skip "$2";             shift ;;
+        '-1' | '--onetime'       ) onetime=true ;;
+        '-l' | '--log'           ) log_level="$2";                shift ;;
+        '-c' | '--color'         ) set_bool log_color "$2";       shift ;;
+        '-M' | '--bl-max'        ) set_num maxbright "$2";        shift ;;
+        '-m' | '--bl-min'        ) set_num minbright "$2";        shift ;;
+        '-C' | '--max-color'     ) set_num max_color "$2";        shift ;;
+        '--calibrate'            ) ctl_action=cal ;;
+        '-s' | '--smooth'        ) set_int_list fade_frames "$2"; shift ;;
+        '-T' | '--threshold'     ) set_int threshold "$2";        shift ;;
+        '-a' | '--acpi-dev'      ) acpi_dev="$2";                 shift ;;
+        '-v' | '--video-dev'     ) vdev="$2";                     shift ;;
+        '-b' | '--backends'      ) backends="$2";                 shift ;;
+        '-B' | '--list-backends' ) print "${backends_all}";       exit  ;;
+        '-t' | '--toggle'        ) ctl_action=toggle;;
+        '-w' | '--watchconf'     ) set_bool watch_conf "$2";      shift ;;
+        '-u' | '--update-conf'   ) save_config ;;
+        '-p' | '--pretend'       ) ctl_action=pretend ;;
+        '-h' | '--help'          ) show_help;                     exit  ;;
+        '--'                     ) backend_args="$*";             break ;;
+        *                        ) echo "Invalid option '$1'" ;;
         esac
         shift
 done
 
 # Configure terminal font controls
 
-if $log_color && ! cmd_avail tput; then
+if "$log_color" && ! cmd_avail tput; then
         log_color=false
 fi
-if ! $log_color; then
+if ! "$log_color"; then
         tput() { :; }
 fi
 
@@ -226,16 +223,16 @@ i=0; for c in black red green yellow blue pink cyan gray; do
 done; unset i c
 # color set helper
 col() {
-        if isnum $1; then
-                tput setaf $1
+        if isnum "$1"; then
+                tput setaf "$1"
         else
-                eval tput setaf \$$1
+                eval "tput setaf \${$1}"
         fi
         if [ $# -gt 2 ]; then
-                if isnum $2; then
-                        tput setab $2
+                if isnum "$2"; then
+                        tput setab "$2"
                 else
-                        eval tput setab \$$2
+                        eval "tput setab \${$2}"
                 fi
         fi
 }
@@ -246,13 +243,13 @@ sgr0="$(tput sgr0)"
 # Loging features
 
 i=0; for l in error warning info debug; do
-        eval $l=$i
+        eval "$l=$i"
         i=$(( i+1 ))
 done; unset i l
-eval log_level_n=\$$log_level
+eval "log_level_n=\${$log_level}"
 
 msg_color() {
-        local c=$1
+        local c="$1"
         shift
         print "$(col $c)$*$sgr0"
 }
@@ -271,7 +268,7 @@ msg_info "Config file: ${bold}$(col green)${config_file}"
 # Depepdency check
 
 # core depepdencies
-msg_info "Checking dependencies"
+msg_info 'Checking dependencies'
 for dep in tr ffmpeg awk v4l2-ctl cat tail; do
         if ! cmd_avail "$dep"; then
                 msg_error "${dep} executable required but not found"
@@ -297,7 +294,7 @@ case "$hextool" in
         ;;
         * )
                 abort=1
-                msg_error "Either hexdump or od are required"
+                msg_error 'Either hexdump or od are required'
         ;;
 esac
 if [ "$abort" ]; then
@@ -310,14 +307,14 @@ msg_debug "byteorder_test: ${byteorder_test}"
 # config watch (optional)
 if $watch_conf && ! cmd_avail inotifywait; then
         watch_conf=false
-        msg_warning "Command 'inotifywait' is not found. Configuration watch will not work."
+        msg_warning 'Command "inotifywait" is not found. Configuration watch will not work.'
 fi
 
 # Choose backlight control tool
 
-msg_info "Searching usable backend"
+msg_info 'Searching usable backend'
 if [ ! "${backends}" ]; then
-        fatal "Backends are not set"
+        fatal 'Backends are not set'
 fi
 for backend in $( print "$backends" | tr ',' ' ' ) ; do
         msg_info "Checking backend ${bold}$(col green)$backend"
@@ -327,23 +324,23 @@ for backend in $( print "$backends" | tr ',' ' ' ) ; do
         light )
                 type ${backend} >/dev/null 2>&1 || continue
                 bl_get_cmd='light -G'
-                bl_sh="sh"
+                bl_sh='sh'
                 bl_fmt="light -S %f ${backend_args}\n"
                 break
         ;;
         xbacklight )
                 type ${backend} >/dev/null 2>&1 || continue
                 bl_get_cmd='xbacklight -get'
-                bl_sh="sh"
+                bl_sh='sh'
                 bl_fmt="xbacklight -set %f ${backend_args}\n"
                 break
         ;;
         internal )
-                acpi_dir="/sys/class/backlight"
+                acpi_dir='/sys/class/backlight'
 
                 # ACPI dir exists and is not empty
                 if ! [ -d "${acpi_dir}" ] ; then
-                        msg_error "No ACPI support found"
+                        msg_error 'No ACPI support found'
                         break
                 fi
 
@@ -354,7 +351,7 @@ for backend in $( print "$backends" | tr ',' ' ' ) ; do
                 else
                         for acpi_dir in "${acpi_dir}"/* ; do break; done
                         if ! [ -d "${acpi_dir}" -a -f "${acpi_dir}/brightness" ]; then
-                                msg_error "No ACPI backlight devices found"
+                                msg_error 'No ACPI backlight devices found'
                                 break
                         fi
                 fi
@@ -378,7 +375,7 @@ for backend in $( print "$backends" | tr ',' ' ' ) ; do
         backend=
 done
 if [ ! "${backend}" ]; then
-        fatal "No working backends found"
+        fatal 'No working backends found'
 fi
 
 msg_info "Using backend ${bold}$(col green)${backend}"
@@ -388,7 +385,7 @@ msg_debug "bl_fmt    : $bl_fmt"
 
 # onetime tuning 
 if $onetime; then
-        msg_info "One-time mode"
+        msg_info 'One-time mode'
 fi
 if [ "$fade_frames" != 0 -a "$bl_min" = 0 ]; then
         msg_warning "Minimum backlight can't be zero when fade is enabled. Set to 1 (of max $bl_max)"
@@ -397,7 +394,7 @@ fi
 
 # Setup temporary dir
 
-for path in "/var/run" "${XDG_RUNTIME_DIR}" "/tmp" "~/.cache"; do
+for path in '/var/run' "${XDG_RUNTIME_DIR}" '/tmp' "$HOME/.cache"; do
         # Check base path
         [ "${path}" -a -d "${path}" -a -w "${path}" ] || continue
         tmpdir="${path}/${progname}"
@@ -422,7 +419,7 @@ elif ! [ -d "${path}" -a -w "${path}" ]; then
 elif [ -f "$pidfile" ]; then
         # We are singleton
 
-        read pid < $pidfile
+        read pid < "$pidfile"
         if [ "$pid" -a "$pid" != 0 -a "$(ps -o pid= $pid | grep $pid)" ] ; then
                 case $ctl_action in
 
@@ -431,7 +428,7 @@ elif [ -f "$pidfile" ]; then
 
                 cal   ) kill -s USR2 $pid ;;
 
-                *     ) msg_warning "Found runing instance, exiting." ;;
+                *     ) msg_warning 'Found runing instance, exiting.' ;;
 
                 esac
                 exit
@@ -457,9 +454,9 @@ input_max() {
         kill -- -$procpid
 }
 
-trap "quit"    INT TERM QUIT HUP
-trap "restart" USR1
-trap "input_max" USR2
+trap 'quit'      INT TERM QUIT HUP
+trap 'restart'   USR1
+trap 'input_max' USR2
 
 # Processing pipeline
 
@@ -618,7 +615,7 @@ fi
 # Monitor config changes
 if $watch_conf && [ -n "$config_file" ]; then {
         inotifywait -q -e modify "$config_file"
-        msg_info "Configuration changed"
+        msg_info 'Configuration changed'
         kill -s USR1 $$
 } & monpid=$!; fi
 
@@ -627,7 +624,7 @@ set +m
 
 # Waiting
 
-msg_debug "Waiting for events"
+msg_debug 'Waiting for events'
 wait $procpid
 if [ -n "$monpid" ]; then
         kill -- -$monpid
